# Generated by Django 4.1 on 2022-09-12 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiantepublica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.estudiante')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.noticias')),
            ],
        ),
    ]
